name: Repo Health Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Shell Script
        run: bash check.sh
